module.exports = {
  apps: [
    {
      name: "burker-watches",
      script: "/root/.nvm/versions/node/v24.13.1/bin/node",
      args: ".next/standalone/server.js",
      cwd: "/var/www/burker-watches.ru",
      env: {
        NODE_ENV: "production",
        PORT: 3010,
        PATH: "/root/.nvm/versions/node/v24.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        DATABASE_URL: "file:/var/lib/burker-watches/dev.db",
        ADMIN_USERNAME: "admin",
        ADMIN_PASSWORD: "admin123",
        ADMIN_JWT_SECRET: "h2VCZGvF/Kp7DQNgT7+4Q3xgBfwZ",
        CRON_SECRET: "ПОДСТАВЬТЕ_ВАШ_СЕКРЕТ_ДЛЯ_CRON",
        ADMIN_EMAIL: "info@kondratov.online",
        NEXT_PUBLIC_SITE_URL: "https://burker-watches.ru",
        MAILOPOST_API_TOKEN: "0e214eeceb83783a7ed4dc025a0175b",
        MAILOPOST_FROM_EMAIL: "info@kondratov.online",
        MAILOPOST_FROM_NAME: "Mira Brands | Burker",
        SMTP_HOST: "smtp.msndr.net",
        SMTP_PORT: 465,
        SMTP_SECURE: true,
        SMTP_USER: "info@kondratov.online",
        SMTP_PASSWORD: "0e214eeceb83783a7ed4dc025a0175b1",
        TELEGRAM_BOT_TOKEN: "8788264025:AAFgPKWEroi0rvGDulpJGcNmTckz7kgBCFU",
        TELEGRAM_CHAT_ID: "-5199924376",
      },
      error_file: "/root/.pm2/logs/burker-watches-error.log",
      out_file: "/root/.pm2/logs/burker-watches-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_memory_restart: "1G",
      instances: 1,
      exec_mode: "fork",
    },
  ],
};
