import { Product } from "./types";

export const products: Product[] = [
  // Isabell коллекция
  {
    id: "isabell-gold-burgundy",
    name: "Isabell Gold Burgundy",
    collection: "Isabell",
    price: 32.7,
    originalPrice: 109.0,
    discount: 70,
    colors: ["золото"],
    images: ["/products/isabell-gold-burgundy.jpg"],
    inStock: true,
  },
  {
    id: "isabell-gold",
    name: "Isabell Gold",
    collection: "Isabell",
    price: 32.7,
    originalPrice: 109.0,
    discount: 70,
    colors: ["золото"],
    images: ["/products/isabell-gold.jpg"],
    inStock: true,
  },
  {
    id: "isabell-petite-gold-burgundy",
    name: "Isabell Petite Gold Burgundy",
    collection: "Isabell",
    price: 54.5,
    originalPrice: 109.0,
    discount: 50,
    colors: ["золото"],
    images: ["/products/isabell-petite-gold-burgundy.jpg"],
    inStock: true,
    variant: "Petite",
    rating: 4.8,
    reviewsCount: 41,
    description: "Элегантные женские часы Isabell Petite с премиальным дизайном. Компактный размер идеально подходит для тонкого запястья.",
    specifications: {
      dimensions: "29 мм x 10 мм",
      material: "Нержавеющая сталь",
      waterResistant: "30 м",
      warranty: "1 год",
    },
    relatedProducts: ["ava-gold-burgundy"],
  },
  // Macy коллекция
  {
    id: "macy-gold-white",
    name: "Macy Gold White",
    collection: "Macy",
    price: 43.6,
    originalPrice: 109.0,
    discount: 60,
    colors: ["золото"],
    images: ["/products/macy-gold-white.jpg"],
    inStock: true,
  },
  {
    id: "macy-gold-burgundy",
    name: "Macy Gold Burgundy",
    collection: "Macy",
    price: 43.6,
    originalPrice: 109.0,
    discount: 60,
    colors: ["золото"],
    images: ["/products/macy-gold-burgundy.jpg"],
    inStock: true,
  },
  {
    id: "macy-petite-gold-burgundy",
    name: "Macy Petite Gold Burgundy",
    collection: "Macy",
    price: 54.5,
    originalPrice: 109.0,
    discount: 50,
    colors: ["золото"],
    images: ["/products/macy-petite-gold-burgundy.jpg"],
    inStock: true,
    variant: "Petite",
  },
  // Olivia коллекция
  {
    id: "olivia-gold-white",
    name: "Olivia Gold White",
    collection: "Olivia",
    price: 38.15,
    originalPrice: 109.0,
    discount: 65,
    colors: ["золото"],
    images: ["/products/olivia-gold-white.jpg"],
    inStock: true,
  },
  {
    id: "olivia-gold-burgundy",
    name: "Olivia Gold Burgundy",
    collection: "Olivia",
    price: 43.6,
    originalPrice: 109.0,
    discount: 60,
    colors: ["золото"],
    images: ["/products/olivia-gold-burgundy.jpg"],
    inStock: true,
  },
  // Julia коллекция
  {
    id: "julia-gold-burgundy",
    name: "Julia Gold Burgundy",
    collection: "Julia",
    price: 43.6,
    originalPrice: 109.0,
    discount: 60,
    colors: ["золото"],
    images: ["/products/julia-gold-burgundy.jpg"],
    inStock: true,
  },
  {
    id: "julia-gold-white",
    name: "Julia Gold White",
    collection: "Julia",
    price: 32.7,
    originalPrice: 109.0,
    discount: 70,
    colors: ["золото"],
    images: ["/products/julia-gold-white.jpg"],
    inStock: true,
  },
  // Ruby коллекция
  {
    id: "ruby-gold-burgundy",
    name: "Ruby Gold Burgundy",
    collection: "Ruby",
    price: 21.8,
    originalPrice: 109.0,
    discount: 80,
    colors: ["золото"],
    images: ["/products/ruby-gold-burgundy.jpg"],
    inStock: true,
  },
  {
    id: "ruby-petite-gold-burgundy",
    name: "Ruby Petite Gold Burgundy",
    collection: "Ruby",
    price: 21.8,
    originalPrice: 109.0,
    discount: 80,
    colors: ["золото"],
    images: ["/products/ruby-petite-gold-burgundy.jpg"],
    inStock: true,
    variant: "Petite",
  },
  // Украшения
  {
    id: "ava-gold-burgundy",
    name: "Ava Gold Burgundy",
    collection: "Украшения",
    price: 11.7,
    originalPrice: 39.0,
    discount: 70,
    colors: ["золото"],
    images: ["/products/ava-gold-burgundy.jpg"],
    inStock: true,
    rating: 4.5,
    reviewsCount: 28,
  },
  {
    id: "violet-bracelet",
    name: "Violet Bracelet",
    collection: "Украшения",
    price: 7.8,
    originalPrice: 39.0,
    discount: 80,
    colors: ["золото", "серебро", "розовое золото"],
    images: ["/products/violet-bracelet.jpg"],
    inStock: true,
  },
];
